/**
 * Human-facing renderings: an ASCII grid preview (so the layout can be checked
 * before importing) and a standalone HTML document with the clickable link
 * (matching iReal Pro's own export styling).
 */
import type { Chart, Measure } from "./types.js";

const SECTION_LABELS: Record<string, string> = {
  A: "A", B: "B", C: "C", D: "D", V: "Verse", i: "Intro",
};

/** A short display string for one measure's contents. */
function measureLabel(m: Measure): string {
  if (m.noChord) return "N.C.";
  if (m.repeatPrevious === "measure") return "%";
  if (m.repeatPrevious === "twoMeasures") return "%%";
  const chords = (m.chords ?? []).map((c) => c.trim()).filter(Boolean);
  if (chords.length === 0) return "/";
  return chords.join("  ");
}

/**
 * Render the chart as a fixed-width ASCII grid, `measuresPerLine` measures per
 * row, so a reader can verify the 4-bars-per-line layout at a glance.
 */
export function asciiFromMeasures(chart: Chart): string {
  const measures = chart.measures ?? [];
  const perLine = chart.measuresPerLine ?? 4;

  const labels = measures.map(measureLabel);
  const colWidth = Math.max(8, ...labels.map((l) => l.length));

  const lines: string[] = [];
  lines.push(`${chart.title}${chart.key ? `  (${chart.key})` : ""}  [${chart.style ?? "Medium Swing"}]`);
  lines.push("");

  for (let i = 0; i < measures.length; i += perLine) {
    const rowMeasures = measures.slice(i, i + perLine);
    const rowLabels = labels.slice(i, i + perLine);

    // Section/ending annotations above the row, if any.
    const ann = rowMeasures
      .map((m, j) => {
        const tags: string[] = [];
        if (m.section) tags.push(`*${SECTION_LABELS[m.section] ?? m.section}`);
        if (m.ending !== undefined) tags.push(`${m.ending}.`);
        if (m.open === "{") tags.push("|:");
        if (m.close === "}") tags.push(":|");
        return tags.join(" ").padEnd(colWidth);
      })
      .join("   ");
    if (ann.trim()) lines.push("   " + ann);

    const cells = rowLabels.map((l) => l.padEnd(colWidth)).join(" | ");
    lines.push("| " + cells + " |");
  }

  return lines.join("\n");
}

/** Escape text for safe inclusion in HTML. */
function htmlEscape(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

/** Build a standalone HTML document containing the import link. */
export function htmlDocument(opts: {
  title: string;
  composer?: string;
  style?: string;
  url: string;
  asciiPreview?: string;
}): string {
  const title = htmlEscape(opts.title);
  const sub = [opts.composer, opts.style]
    .filter((x): x is string => Boolean(x))
    .map(htmlEscape)
    .join(" — ");
  const preview = opts.asciiPreview
    ? `  <pre class="preview">${htmlEscape(opts.asciiPreview)}</pre>\n`
    : "";

  return `<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <style type="text/css">
    body {
      color: rgb(230, 227, 218);
      background-color: rgb(27, 39, 48);
      font-family: Helvetica, Arial, sans-serif;
      padding: 2rem;
    }
    a { text-decoration: none; }
    a:link { color: #94d5ff; }
    a:visited, a:active { color: #b2e0ff; }
    .sub { color: #999; font-size: small; }
    .preview { color: #cfe8d6; background: rgba(0,0,0,0.25); padding: 1rem; border-radius: 6px; overflow-x: auto; }
    .info { font-size: small; color: #999; margin-top: 2rem; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  ${sub ? `<p class="sub">${sub}</p>` : ""}
  <p><a href="${opts.url}">Open in iReal Pro &raquo;</a></p>
${preview}  <p class="info">Generated by ireal-mcp. Tap the link on a device with iReal Pro installed to import.</p>
</body>
</html>
`;
}

const PAGE_STYLE = `
    body { color: rgb(230,227,218); background-color: rgb(27,39,48);
           font-family: Helvetica, Arial, sans-serif; padding: 1.5rem; max-width: 60rem; margin: 0 auto; }
    a { text-decoration: none; }
    a:link { color: #94d5ff; } a:visited, a:active { color: #b2e0ff; }
    h1 { margin-bottom: 0.2rem; }
    .sub { color: #999; font-size: small; margin-top: 0; }
    .preview { color: #cfe8d6; background: rgba(0,0,0,0.25); padding: 1rem;
               border-radius: 6px; overflow-x: auto; font-size: 0.95rem; }
    .import { display: inline-block; background: #1f6fb2; color: #fff !important;
              padding: 0.7rem 1.1rem; border-radius: 8px; font-weight: bold; margin: 0.5rem 0; }
    ul.charts { list-style: none; padding: 0; }
    ul.charts li { padding: 0.6rem 0; border-bottom: 1px solid rgba(255,255,255,0.08); }
    ul.charts .meta { color: #999; font-size: small; }
    .topbar { display: flex; justify-content: space-between; align-items: baseline; flex-wrap: wrap; gap: 0.5rem; }
    .info { font-size: small; color: #999; margin-top: 2rem; }
    .featured { background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.1);
                border-radius: 10px; padding: 1rem 1.25rem; margin: 0.5rem 0 1.5rem; }
    .featured h2 { margin: 0.2rem 0; }
    h3 { margin-top: 1.5rem; border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 0.3rem; }
    .badge { font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.04em;
             padding: 0.1rem 0.45rem; border-radius: 999px; vertical-align: middle; }
    .badge-straight { background: #2f4a3a; color: #bfe9cf; }
    .badge-embellished { background: #4a3a2f; color: #e9d3bf; }
    .mono { font-family: ui-monospace, Menlo, Consolas, monospace; }
    ul.plan li { margin: 0.3rem 0; }
    ul.cells { color: #cfe0e8; }
    table.analysis { border-collapse: collapse; width: 100%; margin-top: 0.5rem; }
    table.analysis th, table.analysis td { text-align: left; padding: 0.4rem 0.6rem;
        border-bottom: 1px solid rgba(255,255,255,0.08); vertical-align: top; }
    table.analysis th { color: #999; font-weight: normal; font-size: small; }
    table.analysis tr.borrowed td { background: rgba(233,211,191,0.08); }
    .onescale { background: rgba(148,213,255,0.08); border-left: 3px solid #94d5ff;
                padding: 0.6rem 0.9rem; border-radius: 4px; margin: 0.6rem 0; }
`;

interface IndexChart {
  slug: string;
  title: string;
  composer?: string;
  style?: string;
  key?: string;
  variant?: "straight" | "embellished";
  savedAt?: string;
  asciiPreview?: string;
  irealbUrl?: string;
}

function variantBadge(variant?: string): string {
  if (!variant) return "";
  return ` <span class="badge badge-${variant}">${variant}</span>`;
}

function metaLine(c: IndexChart): string {
  return [c.composer, c.style, c.key ? `Key ${c.key}` : ""]
    .filter((x): x is string => Boolean(x))
    .map(htmlEscape)
    .join(" · ");
}

function whenLabel(savedAt?: string): string {
  if (!savedAt) return "";
  // Show the date portion (YYYY-MM-DD) — enough to sort/scan by.
  return savedAt.slice(0, 10);
}

/**
 * The library index page. The most recently updated chart is featured at the
 * top (with preview + import); every chart is listed below, newest first.
 * `charts` is expected to be pre-sorted by recency (newest first).
 */
export function indexHtml(charts: IndexChart[], opts: { playlistHref?: string } = {}): string {
  const featured = charts[0];

  const featuredBlock = featured
    ? `  <div class="featured">
    <div class="meta">Most recent${featured.savedAt ? ` · updated ${whenLabel(featured.savedAt)}` : ""}</div>
    <h2><a href="/chart/${encodeURIComponent(featured.slug)}">${htmlEscape(featured.title)}</a>${variantBadge(featured.variant)}</h2>
    <div class="meta">${metaLine(featured)}</div>
    ${featured.irealbUrl ? `<p><a class="import" href="/import/${encodeURIComponent(featured.slug)}">Open in iReal Pro &raquo;</a></p>` : ""}
    ${featured.asciiPreview ? `<pre class="preview">${htmlEscape(featured.asciiPreview)}</pre>` : ""}
  </div>`
    : "";

  const rows = charts.length
    ? charts
        .map((c, i) => {
          const tag = i === 0 ? ` <span class="meta">(latest)</span>` : "";
          const when = c.savedAt ? `<span class="meta"> · ${whenLabel(c.savedAt)}</span>` : "";
          return `    <li>
      <a href="/chart/${encodeURIComponent(c.slug)}"><strong>${htmlEscape(c.title)}</strong></a>${variantBadge(c.variant)}${tag}
      &nbsp; <a href="/import/${encodeURIComponent(c.slug)}">import &raquo;</a>
      <div class="meta">${metaLine(c)}${when}</div>
    </li>`;
        })
        .join("\n")
    : `    <li class="meta">No charts yet. Create one with the create_chart tool.</li>`;

  const playlist =
    charts.length && opts.playlistHref
      ? `  <p><a class="import" href="${opts.playlistHref}">Open all ${charts.length} as one iReal Pro playlist &raquo;</a></p>`
      : "";

  return `<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>iReal Pro charts</title>
  <style type="text/css">${PAGE_STYLE}</style>
</head>
<body>
  <div class="topbar"><h1>iReal Pro charts</h1></div>
${featuredBlock}
${playlist}
  <h3>All charts (${charts.length}) <span class="meta">— newest first</span></h3>
  <ul class="charts">
${rows}
  </ul>
  <p class="info">Served by ireal-mcp. Tap import links on a device with iReal Pro installed.</p>
</body>
</html>
`;
}

/** Render the harmonic analysis as an HTML section. */
export function analysisHtml(analysis: AnalysisLike | undefined): string {
  if (!analysis) return "";

  const planItems = analysis.jamPlan.map((p) => `      <li>${htmlEscape(p)}</li>`).join("\n");
  const cells = analysis.cells.length
    ? `    <p class="meta">Cadences &amp; cells</p>
    <ul class="cells">
${analysis.cells.map((c) => `      <li>${htmlEscape(c)}</li>`).join("\n")}
    </ul>`
    : "";

  const rows = analysis.chords
    .map(
      (c) => `      <tr${c.scaleChange ? ' class="borrowed"' : ""}>
        <td><strong>${htmlEscape(c.symbol)}</strong></td>
        <td>${htmlEscape(c.roman)}</td>
        <td>${htmlEscape(c.function)}</td>
        <td>${c.scaleChange ? "<strong>scale change → </strong>" : ""}${htmlEscape(c.scale)}<div class="meta mono">${htmlEscape(c.scaleNotes)}</div>${c.note ? `<div class="meta">${htmlEscape(c.note)}</div>` : ""}</td>
      </tr>`,
    )
    .join("\n");

  const penta = analysis.homePentatonic
    ? `<br>Shortcut: ${htmlEscape(analysis.homePentatonic)} — <span class="mono">${htmlEscape(analysis.homePentatonicNotes ?? "")}</span>`
    : "";

  return `  <h3>Analysis &amp; jam plan</h3>
  <div class="onescale">One scale for the whole tune: <strong>${htmlEscape(analysis.homeScale)}</strong> — <span class="mono">${htmlEscape(analysis.homeScaleNotes)}</span>${penta}</div>
  <ul class="plan">
${planItems}
  </ul>
${cells}
  <table class="analysis">
    <thead><tr><th>Chord</th><th>Roman</th><th>Function</th><th>Scale to play</th></tr></thead>
    <tbody>
${rows}
    </tbody>
  </table>
`;
}

interface AnalysisLike {
  homeKeyLabel?: string;
  homeScale: string;
  homeScaleNotes: string;
  homePentatonic?: string;
  homePentatonicNotes?: string;
  jamPlan: string[];
  cells: string[];
  chords: {
    symbol: string;
    roman: string;
    function: string;
    scale: string;
    scaleNotes: string;
    borrowed: boolean;
    scaleChange?: boolean;
    note?: string;
  }[];
}

/** A single served chart page (view, with a prominent import button + preview). */
export function chartPageHtml(record: {
  title: string;
  composer?: string;
  style?: string;
  key?: string;
  variant?: "straight" | "embellished";
  slug: string;
  irealbUrl: string;
  asciiPreview: string;
  analysis?: AnalysisLike;
}): string {
  const title = htmlEscape(record.title);
  const sub = [record.composer, record.style, record.key ? `Key ${record.key}` : ""]
    .filter((x): x is string => Boolean(x))
    .map(htmlEscape)
    .join(" — ");

  return `<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <style type="text/css">${PAGE_STYLE}</style>
</head>
<body>
  <p><a href="/">&laquo; All charts</a></p>
  <h1>${title}${variantBadge(record.variant)}</h1>
  ${sub ? `<p class="sub">${sub}</p>` : ""}
  <p><a class="import" href="${record.irealbUrl}">Open in iReal Pro &raquo;</a></p>
  <pre class="preview">${htmlEscape(record.asciiPreview)}</pre>
${analysisHtml(record.analysis)}  <p class="info">Tap the button on a device with iReal Pro installed to import this chart.</p>
</body>
</html>
`;
}

/**
 * Best-effort split of a raw progression string into measures (for previews of
 * raw input and for decoded charts). Strips layout symbols and returns the
 * chord-ish tokens per measure.
 */
export function splitProgressionToMeasures(progression: string): { chords: string[] }[] {
  // Remove staff text blocks.
  let p = progression.replace(/<[^>]*>/g, " ");
  // Split on any barline.
  const rawMeasures = p.split(/[\[\]{}|Z]+/);

  // Structural single-letter tokens to drop entirely.
  const STRUCTURAL = new Set(["s", "l", "S", "Q", "f", "Y", "U"]);

  const measures: { chords: string[] }[] = [];
  for (const raw of rawMeasures) {
    let body = raw;
    // Strip multi-char structural tokens (section marks, time sigs, endings).
    body = body.replace(/\*[ABCDVi]/g, " ");
    body = body.replace(/T\d\d/g, " ");
    body = body.replace(/N\d/g, " ");

    // Tokens separated by spaces or commas.
    const tokens = body
      .split(/[\s,]+/)
      .map((t) => t.trim())
      .filter((t) => t.length > 0 && !STRUCTURAL.has(t));

    const chords: string[] = [];
    for (let t of tokens) {
      // Strip a leading size marker attached to a chord (e.g. "sEh", "lD-").
      t = t.replace(/^[sl](?=[A-G])/, "");
      if (t === "n") chords.push("N.C.");
      else if (t === "x") chords.push("%");
      else if (t === "r") chords.push("%%");
      else if (t === "p") chords.push("/");
      else if (t.length > 0) chords.push(t);
    }

    if (chords.length > 0) measures.push({ chords });
  }
  return measures;
}
